/*
 * store — per-user record of saved shares.
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 * All of this is unprivileged and lives in the user's own session. It holds
 * no secrets: a share's password is written once, over the KAuth call, into
 * the root-owned credential file the helper creates, and is never stored
 * here. (It used to be kept in KWallet for sign-in-scoped shares; that whole
 * mode is gone — a saved share is armed at boot, so there is no per-session
 * secret left to hold.)
 *
 * Records are keyed by a stable per-share id (plan §5.1), not by mount point
 * or "username@unc" — the latter is shared by two configured shares of the
 * same share and user, so deleting either would revoke both. The id is
 * root-generated by the helper and returned from `definesystem` (plan
 * §1.6.2); Store never invents one of its own, so a definition and its config
 * record can never disagree about identity.
 *
 * Everything here is user-writable convenience data, not authoritative: the
 * root-owned unit marker decides mode, authentication and ownership (plan
 * §6.1, §13). A caller that finds Store disagreeing with the marker must
 * trust the marker and report the row as Drift — Store is not consulted for
 * that decision.
 */

#pragma once

#include <QList>
#include <QString>

namespace Store
{

/** One saved share, as recorded in ~/.config/nasmountrc. */
struct Share {
    QString id; ///< root-generated by the helper; stable for the life of the share
    QString unc;
    QString mountPoint;
    QString username;
    QString domain;
    /** "readwrite" | "readonly" | "readwrite-executable"
     *  (UnitValue::accessModeToString()). Convenience only: the marker is
     *  authoritative, and MountModel reports a disagreement as drift rather
     *  than trusting this. A record written before 0.1.4 has no `Access` key
     *  at all and reads back as "readwrite", which is what those shares are. */
    QString access;
};

/**
 * A share as read from config, together with the generation it was read at —
 * the token a later checked commit must present unchanged for the write to
 * succeed (plan §1.6.3). `exists` is false for an id with no record at all.
 * `corrupt` is true for a group that is present but missing a required field
 * (empty Unc or MountPoint) — surfaced, never silently skipped (plan
 * §1.6.5); `share` on a corrupt snapshot carries whatever fields were
 * readable, for display, but must not be trusted as a complete record.
 */
struct Snapshot {
    Share share;
    quint64 generation = 0;
    bool exists = false;
    bool corrupt = false;
};

/**
 * Every share group in config, in the order KConfig lists them, each as a
 * full Snapshot — including corrupt groups (plan §1.6.5). Callers that only
 * want well-formed, existing shares should filter on `!corrupt`, or use
 * shares() below.
 */
QList<Snapshot> shareSnapshots();

/** Convenience over shareSnapshots(): only the well-formed shares, in the
 *  same order. What every caller before plan §1.6 used. */
QList<Share> shares();

/** Reads one share's current snapshot; `exists` is false if the id has no record. */
Snapshot snapshotById(const QString &id);

enum class CommitResult {
    Ok,
    GenerationConflict, ///< the record changed since it was read; the caller's snapshot is stale
    SyncFailed,         ///< KConfig::sync() itself failed -- a real failure, never silently ignored
};

/**
 * Checked compare-and-swap write of one share record (plan §1.6.3).
 *
 * To insert a brand-new record, pass `expectedGeneration == 0`; this fails
 * with GenerationConflict if a record with `share.id` already exists. To
 * update an existing record, pass exactly the generation a prior
 * snapshotById()/shareSnapshots() call returned for it; this fails with
 * GenerationConflict if that is no longer current (deleted, or written by
 * someone else since). The per-user lock (Session::UserLock) must be held
 * by the caller across the read that produced `expectedGeneration` and this
 * commit — the generation check catches a bug that drops the lock, it does
 * not replace holding it (plan §1.6.4).
 */
CommitResult commitShare(const Share &share, quint64 expectedGeneration, QString *error);

/** Removes a share record. The share's own credential is a root-owned file
 *  under /etc/nasmount, removed by the privileged helper as part of
 *  undefining the definition — this only clears the local convenience
 *  record. */
bool removeShare(const QString &id);

/** Removes the configuration file. Checked; used only by the authenticated
 *  uninstall path. */
bool purgeApplicationData(QString *error);

} // namespace Store
